version: "3"
services:
  postgresql:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=pretia
      - POSTGRES_PASSWORD=pretia
    ports:
      - "4103:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./initdb.d/:/docker-entrypoint-initdb.d/

  jwt-api:
    restart: unless-stopped
    build: jwt-api
    volumes:
      - ./jwt-api/src:/app/src
    depends_on:
      - postgresql
    environment:
      ACCESS_TOKEN_MINUTES: 1440
      DATABASE_URL: postgres://pretia:pretia@postgresql:5432/pretia
      JWT_SECRET: k7AUFcjtTcBvvLBJHeuS9vrD5DwF9WLB
      WEB_URL: http://localhost:4100

    ports:
      - 4101:4101

volumes:
  database-data:
